/********************************************************************************
** Form generated from reading ui file 'ImageVis3D.ui'
**
** Created: Thu 5. Jun 10:27:47 2008
**      by: Qt User Interface Compiler version 4.4.0
**
** WARNING! All changes made in this file will be lost when recompiling ui file!
********************************************************************************/

#ifndef UI_IMAGEVIS3D_H
#define UI_IMAGEVIS3D_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QCheckBox>
#include <QtGui/QComboBox>
#include <QtGui/QDockWidget>
#include <QtGui/QGraphicsView>
#include <QtGui/QGridLayout>
#include <QtGui/QGroupBox>
#include <QtGui/QHBoxLayout>
#include <QtGui/QLCDNumber>
#include <QtGui/QLabel>
#include <QtGui/QListWidget>
#include <QtGui/QMainWindow>
#include <QtGui/QMenu>
#include <QtGui/QMenuBar>
#include <QtGui/QPushButton>
#include <QtGui/QSpinBox>
#include <QtGui/QStatusBar>
#include <QtGui/QTabWidget>
#include <QtGui/QToolButton>
#include <QtGui/QVBoxLayout>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *actionWerwer;
    QAction *actionCreate_New_Project;
    QAction *actionOpen_Existing_Project;
    QAction *actionLast_Used_Projects;
    QAction *actionSave_Current_Project;
    QAction *actionLoad_Dataset;
    QAction *actionSave_Dataset;
    QAction *actionQuit;
    QAction *actionClose_Dataset;
    QAction *actionClose_Project;
    QAction *action2_x_2_View;
    QAction *action1_x_3_Viw;
    QAction *actionSinge_View;
    QAction *actionDirect_Volume_Rendering;
    QAction *actionIsosurface_Rendering;
    QAction *actionCrop;
    QAction *actionMask;
    QAction *actionBox;
    QAction *actionPoly_Line;
    QAction *actionSelect_All;
    QAction *actionDelete_Selection;
    QAction *actionInvert_Selection;
    QAction *actionHistorgram;
    QAction *actionStastistcs;
    QAction *actionUndo;
    QAction *actionRedo;
    QAction *actionGenerate_Movie;
    QAction *actionREcord_Image;
    QAction *actionGo_Fullscreen;
    QAction *actionRecord_Movie;
    QAction *actionMedian;
    QAction *actionGaussian;
    QAction *actionEdge_Detection;
    QAction *actionDesign_Convolution;
    QAction *actionLoad_Convolution;
    QAction *actionSave_Convolution;
    QAction *actionAnd;
    QAction *actionOr;
    QAction *actionNot;
    QAction *actionXor;
    QAction *actionLoad_Transfer_Function;
    QAction *actionAbout;
    QAction *actionOpen_Online_Help;
    QAction *actionLoad;
    QAction *actionSave;
    QAction *action1D_Transfer_Function_Editor;
    QAction *action2D_Transfer_Function_Editor;
    QAction *actionToggle_between_1D_and_2D;
    QAction *actionStereo_Projection;
    QAction *actionIsosurface;
    QAction *actionPoly_line;
    QAction *actionPaint_brush;
    QAction *actionInformation;
    QAction *actionInvert;
    QAction *actionGeneric;
    QAction *actionResample;
    QAction *actionHistogram;
    QWidget *centralwidget;
    QWidget *widget_2By2;
    QWidget *layoutWidget;
    QGridLayout *Grid_2By2;
    QGraphicsView *graphicsView_5;
    QGraphicsView *graphicsView_6;
    QGraphicsView *graphicsView_2;
    QGraphicsView *graphicsView_3;
    QWidget *widget_Single;
    QGraphicsView *graphicsView_9;
    QWidget *widget_3By1;
    QWidget *layoutWidget1;
    QGridLayout *Grid_3By1;
    QGraphicsView *graphicsView_8;
    QGraphicsView *graphicsView;
    QGraphicsView *graphicsView_4;
    QGraphicsView *graphicsView_7;
    QMenuBar *menubar;
    QMenu *menu_File;
    QMenu *menu_View;
    QMenu *menu_Tools;
    QMenu *menuBitwise_Operations;
    QMenu *menuMasking;
    QMenu *menu_Filters;
    QMenu *menu_Help;
    QMenu *menuSelection;
    QMenu *menuRecording;
    QMenu *menuTransfer_Functions;
    QStatusBar *statusbar;
    QDockWidget *dockWidget;
    QWidget *dockWidgetContents;
    QHBoxLayout *horizontalLayout;
    QTabWidget *tab_widget;
    QWidget *history_tab;
    QGridLayout *gridLayout;
    QListWidget *listWidget;
    QPushButton *pushButton_3;
    QPushButton *pushButton_4;
    QWidget *tools_tab;
    QWidget *polyline_tool_widget;
    QLabel *label_7;
    QCheckBox *checkBox;
    QToolButton *toolButton;
    QToolButton *toolButton_2;
    QToolButton *toolButton_3;
    QToolButton *toolButton_4;
    QCheckBox *checkBox_3;
    QToolButton *polyline_close_Button;
    QWidget *Cursor_information_widget;
    QLabel *label_2;
    QLCDNumber *lcdNumber;
    QLCDNumber *lcdNumber_2;
    QLCDNumber *lcdNumber_3;
    QLCDNumber *lcdNumber_4;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *label_6;
    QLabel *label_5;
    QWidget *paintbrush_tool_widget;
    QLabel *label_8;
    QCheckBox *checkBox_2;
    QToolButton *toolButton_5;
    QToolButton *toolButton_6;
    QToolButton *Paintbrush_close_Button;
    QLabel *label_9;
    QSpinBox *spinBox;
    QWidget *resample_tool_widget;
    QLabel *label_15;
    QSpinBox *spinBox_5;
    QSpinBox *spinBox_6;
    QLabel *label_16;
    QSpinBox *spinBox_7;
    QLabel *label_17;
    QLabel *label_18;
    QComboBox *comboBox_2;
    QLabel *label_10;
    QToolButton *resample_close_Button;
    QToolButton *toolButton_14;
    QWidget *crop_tool_widget;
    QToolButton *crop_close_Button;
    QToolButton *toolButton_29;
    QLabel *label_28;
    QLCDNumber *lcdNumber_5;
    QLabel *label_27;
    QLabel *label_29;
    QLCDNumber *lcdNumber_6;
    QLabel *label_30;
    QLCDNumber *lcdNumber_7;
    QLCDNumber *lcdNumber_8;
    QLabel *label_31;
    QLabel *label_32;
    QLCDNumber *lcdNumber_9;
    QLabel *label_33;
    QLCDNumber *lcdNumber_10;
    QWidget *Filter_tab;
    QWidget *Gaussian_filter_widget;
    QLabel *label_21;
    QToolButton *guassian_close_Button;
    QToolButton *toolButton_25;
    QLabel *label_22;
    QSpinBox *spinBox_10;
    QSpinBox *spinBox_11;
    QLabel *label_24;
    QWidget *Median_filter_widget;
    QLabel *label_25;
    QToolButton *median_close_Button;
    QToolButton *toolButton_27;
    QLabel *label_26;
    QSpinBox *spinBox_12;
    QWidget *Histogram_filter_widget;
    QLabel *label_19;
    QSpinBox *spinBox_8;
    QSpinBox *spinBox_9;
    QLabel *label_20;
    QLabel *label_23;
    QToolButton *toolButton_12;
    QToolButton *histogram_close_Button;
    QWidget *Recorder_tab;
    QVBoxLayout *verticalLayout_2;
    QGroupBox *groupBox;
    QPushButton *pushButton_5;
    QPushButton *pushButton_6;
    QGroupBox *groupBox_2;
    QPushButton *pushButton_7;
    QPushButton *pushButton_8;
    QPushButton *pushButton_9;
    QPushButton *pushButton_10;
    QLabel *label;
    QPushButton *pushButton_11;
    QPushButton *pushButton_12;
    QPushButton *pushButton_13;

    void setupUi(QMainWindow *MainWindow)
    {
    if (MainWindow->objectName().isEmpty())
        MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
    MainWindow->resize(961, 832);
    QSizePolicy sizePolicy(QSizePolicy::Expanding, QSizePolicy::Expanding);
    sizePolicy.setHorizontalStretch(0);
    sizePolicy.setVerticalStretch(0);
    sizePolicy.setHeightForWidth(MainWindow->sizePolicy().hasHeightForWidth());
    MainWindow->setSizePolicy(sizePolicy);
    MainWindow->setMouseTracking(false);
    MainWindow->setDockNestingEnabled(false);
    MainWindow->setDockOptions(QMainWindow::AllowTabbedDocks|QMainWindow::AnimatedDocks);
    actionWerwer = new QAction(MainWindow);
    actionWerwer->setObjectName(QString::fromUtf8("actionWerwer"));
    actionCreate_New_Project = new QAction(MainWindow);
    actionCreate_New_Project->setObjectName(QString::fromUtf8("actionCreate_New_Project"));
    actionOpen_Existing_Project = new QAction(MainWindow);
    actionOpen_Existing_Project->setObjectName(QString::fromUtf8("actionOpen_Existing_Project"));
    actionLast_Used_Projects = new QAction(MainWindow);
    actionLast_Used_Projects->setObjectName(QString::fromUtf8("actionLast_Used_Projects"));
    actionSave_Current_Project = new QAction(MainWindow);
    actionSave_Current_Project->setObjectName(QString::fromUtf8("actionSave_Current_Project"));
    actionLoad_Dataset = new QAction(MainWindow);
    actionLoad_Dataset->setObjectName(QString::fromUtf8("actionLoad_Dataset"));
    actionSave_Dataset = new QAction(MainWindow);
    actionSave_Dataset->setObjectName(QString::fromUtf8("actionSave_Dataset"));
    actionQuit = new QAction(MainWindow);
    actionQuit->setObjectName(QString::fromUtf8("actionQuit"));
    actionClose_Dataset = new QAction(MainWindow);
    actionClose_Dataset->setObjectName(QString::fromUtf8("actionClose_Dataset"));
    actionClose_Project = new QAction(MainWindow);
    actionClose_Project->setObjectName(QString::fromUtf8("actionClose_Project"));
    action2_x_2_View = new QAction(MainWindow);
    action2_x_2_View->setObjectName(QString::fromUtf8("action2_x_2_View"));
    action1_x_3_Viw = new QAction(MainWindow);
    action1_x_3_Viw->setObjectName(QString::fromUtf8("action1_x_3_Viw"));
    actionSinge_View = new QAction(MainWindow);
    actionSinge_View->setObjectName(QString::fromUtf8("actionSinge_View"));
    actionDirect_Volume_Rendering = new QAction(MainWindow);
    actionDirect_Volume_Rendering->setObjectName(QString::fromUtf8("actionDirect_Volume_Rendering"));
    actionIsosurface_Rendering = new QAction(MainWindow);
    actionIsosurface_Rendering->setObjectName(QString::fromUtf8("actionIsosurface_Rendering"));
    actionCrop = new QAction(MainWindow);
    actionCrop->setObjectName(QString::fromUtf8("actionCrop"));
    actionMask = new QAction(MainWindow);
    actionMask->setObjectName(QString::fromUtf8("actionMask"));
    actionBox = new QAction(MainWindow);
    actionBox->setObjectName(QString::fromUtf8("actionBox"));
    actionPoly_Line = new QAction(MainWindow);
    actionPoly_Line->setObjectName(QString::fromUtf8("actionPoly_Line"));
    actionSelect_All = new QAction(MainWindow);
    actionSelect_All->setObjectName(QString::fromUtf8("actionSelect_All"));
    actionDelete_Selection = new QAction(MainWindow);
    actionDelete_Selection->setObjectName(QString::fromUtf8("actionDelete_Selection"));
    actionInvert_Selection = new QAction(MainWindow);
    actionInvert_Selection->setObjectName(QString::fromUtf8("actionInvert_Selection"));
    actionHistorgram = new QAction(MainWindow);
    actionHistorgram->setObjectName(QString::fromUtf8("actionHistorgram"));
    actionStastistcs = new QAction(MainWindow);
    actionStastistcs->setObjectName(QString::fromUtf8("actionStastistcs"));
    actionUndo = new QAction(MainWindow);
    actionUndo->setObjectName(QString::fromUtf8("actionUndo"));
    actionRedo = new QAction(MainWindow);
    actionRedo->setObjectName(QString::fromUtf8("actionRedo"));
    actionGenerate_Movie = new QAction(MainWindow);
    actionGenerate_Movie->setObjectName(QString::fromUtf8("actionGenerate_Movie"));
    actionREcord_Image = new QAction(MainWindow);
    actionREcord_Image->setObjectName(QString::fromUtf8("actionREcord_Image"));
    actionGo_Fullscreen = new QAction(MainWindow);
    actionGo_Fullscreen->setObjectName(QString::fromUtf8("actionGo_Fullscreen"));
    actionRecord_Movie = new QAction(MainWindow);
    actionRecord_Movie->setObjectName(QString::fromUtf8("actionRecord_Movie"));
    actionMedian = new QAction(MainWindow);
    actionMedian->setObjectName(QString::fromUtf8("actionMedian"));
    actionGaussian = new QAction(MainWindow);
    actionGaussian->setObjectName(QString::fromUtf8("actionGaussian"));
    actionEdge_Detection = new QAction(MainWindow);
    actionEdge_Detection->setObjectName(QString::fromUtf8("actionEdge_Detection"));
    actionDesign_Convolution = new QAction(MainWindow);
    actionDesign_Convolution->setObjectName(QString::fromUtf8("actionDesign_Convolution"));
    actionLoad_Convolution = new QAction(MainWindow);
    actionLoad_Convolution->setObjectName(QString::fromUtf8("actionLoad_Convolution"));
    actionSave_Convolution = new QAction(MainWindow);
    actionSave_Convolution->setObjectName(QString::fromUtf8("actionSave_Convolution"));
    actionAnd = new QAction(MainWindow);
    actionAnd->setObjectName(QString::fromUtf8("actionAnd"));
    actionOr = new QAction(MainWindow);
    actionOr->setObjectName(QString::fromUtf8("actionOr"));
    actionNot = new QAction(MainWindow);
    actionNot->setObjectName(QString::fromUtf8("actionNot"));
    actionXor = new QAction(MainWindow);
    actionXor->setObjectName(QString::fromUtf8("actionXor"));
    actionLoad_Transfer_Function = new QAction(MainWindow);
    actionLoad_Transfer_Function->setObjectName(QString::fromUtf8("actionLoad_Transfer_Function"));
    actionAbout = new QAction(MainWindow);
    actionAbout->setObjectName(QString::fromUtf8("actionAbout"));
    actionOpen_Online_Help = new QAction(MainWindow);
    actionOpen_Online_Help->setObjectName(QString::fromUtf8("actionOpen_Online_Help"));
    actionLoad = new QAction(MainWindow);
    actionLoad->setObjectName(QString::fromUtf8("actionLoad"));
    actionSave = new QAction(MainWindow);
    actionSave->setObjectName(QString::fromUtf8("actionSave"));
    action1D_Transfer_Function_Editor = new QAction(MainWindow);
    action1D_Transfer_Function_Editor->setObjectName(QString::fromUtf8("action1D_Transfer_Function_Editor"));
    action2D_Transfer_Function_Editor = new QAction(MainWindow);
    action2D_Transfer_Function_Editor->setObjectName(QString::fromUtf8("action2D_Transfer_Function_Editor"));
    actionToggle_between_1D_and_2D = new QAction(MainWindow);
    actionToggle_between_1D_and_2D->setObjectName(QString::fromUtf8("actionToggle_between_1D_and_2D"));
    actionStereo_Projection = new QAction(MainWindow);
    actionStereo_Projection->setObjectName(QString::fromUtf8("actionStereo_Projection"));
    actionIsosurface = new QAction(MainWindow);
    actionIsosurface->setObjectName(QString::fromUtf8("actionIsosurface"));
    actionPoly_line = new QAction(MainWindow);
    actionPoly_line->setObjectName(QString::fromUtf8("actionPoly_line"));
    actionPaint_brush = new QAction(MainWindow);
    actionPaint_brush->setObjectName(QString::fromUtf8("actionPaint_brush"));
    actionInformation = new QAction(MainWindow);
    actionInformation->setObjectName(QString::fromUtf8("actionInformation"));
    actionInvert = new QAction(MainWindow);
    actionInvert->setObjectName(QString::fromUtf8("actionInvert"));
    actionGeneric = new QAction(MainWindow);
    actionGeneric->setObjectName(QString::fromUtf8("actionGeneric"));
    actionResample = new QAction(MainWindow);
    actionResample->setObjectName(QString::fromUtf8("actionResample"));
    actionHistogram = new QAction(MainWindow);
    actionHistogram->setObjectName(QString::fromUtf8("actionHistogram"));
    centralwidget = new QWidget(MainWindow);
    centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
    centralwidget->setGeometry(QRect(0, 22, 659, 789));
    widget_2By2 = new QWidget(centralwidget);
    widget_2By2->setObjectName(QString::fromUtf8("widget_2By2"));
    widget_2By2->setGeometry(QRect(0, 0, 1435, 875));
    widget_2By2->setMinimumSize(QSize(1435, 875));
    layoutWidget = new QWidget(widget_2By2);
    layoutWidget->setObjectName(QString::fromUtf8("layoutWidget"));
    layoutWidget->setGeometry(QRect(0, 0, 1131, 831));
    Grid_2By2 = new QGridLayout(layoutWidget);
    Grid_2By2->setSpacing(0);
    Grid_2By2->setMargin(0);
    Grid_2By2->setObjectName(QString::fromUtf8("Grid_2By2"));
    Grid_2By2->setContentsMargins(0, 0, 0, 0);
    graphicsView_5 = new QGraphicsView(layoutWidget);
    graphicsView_5->setObjectName(QString::fromUtf8("graphicsView_5"));
    sizePolicy.setHeightForWidth(graphicsView_5->sizePolicy().hasHeightForWidth());
    graphicsView_5->setSizePolicy(sizePolicy);

    Grid_2By2->addWidget(graphicsView_5, 0, 0, 1, 1);

    graphicsView_6 = new QGraphicsView(layoutWidget);
    graphicsView_6->setObjectName(QString::fromUtf8("graphicsView_6"));
    sizePolicy.setHeightForWidth(graphicsView_6->sizePolicy().hasHeightForWidth());
    graphicsView_6->setSizePolicy(sizePolicy);

    Grid_2By2->addWidget(graphicsView_6, 1, 0, 1, 1);

    graphicsView_2 = new QGraphicsView(layoutWidget);
    graphicsView_2->setObjectName(QString::fromUtf8("graphicsView_2"));
    sizePolicy.setHeightForWidth(graphicsView_2->sizePolicy().hasHeightForWidth());
    graphicsView_2->setSizePolicy(sizePolicy);

    Grid_2By2->addWidget(graphicsView_2, 0, 1, 1, 1);

    graphicsView_3 = new QGraphicsView(layoutWidget);
    graphicsView_3->setObjectName(QString::fromUtf8("graphicsView_3"));
    sizePolicy.setHeightForWidth(graphicsView_3->sizePolicy().hasHeightForWidth());
    graphicsView_3->setSizePolicy(sizePolicy);

    Grid_2By2->addWidget(graphicsView_3, 1, 1, 1, 1);

    widget_Single = new QWidget(centralwidget);
    widget_Single->setObjectName(QString::fromUtf8("widget_Single"));
    widget_Single->setGeometry(QRect(0, 0, 1435, 875));
    widget_Single->setMinimumSize(QSize(1435, 875));
    graphicsView_9 = new QGraphicsView(widget_Single);
    graphicsView_9->setObjectName(QString::fromUtf8("graphicsView_9"));
    graphicsView_9->setGeometry(QRect(0, 0, 1435, 875));
    graphicsView_9->setMinimumSize(QSize(531, 431));
    widget_3By1 = new QWidget(centralwidget);
    widget_3By1->setObjectName(QString::fromUtf8("widget_3By1"));
    widget_3By1->setGeometry(QRect(0, 0, 1435, 875));
    sizePolicy.setHeightForWidth(widget_3By1->sizePolicy().hasHeightForWidth());
    widget_3By1->setSizePolicy(sizePolicy);
    widget_3By1->setMinimumSize(QSize(1435, 875));
    layoutWidget1 = new QWidget(widget_3By1);
    layoutWidget1->setObjectName(QString::fromUtf8("layoutWidget1"));
    layoutWidget1->setGeometry(QRect(0, 1, 1131, 841));
    Grid_3By1 = new QGridLayout(layoutWidget1);
    Grid_3By1->setSpacing(0);
    Grid_3By1->setMargin(0);
    Grid_3By1->setObjectName(QString::fromUtf8("Grid_3By1"));
    Grid_3By1->setContentsMargins(0, 0, 0, 0);
    graphicsView_8 = new QGraphicsView(layoutWidget1);
    graphicsView_8->setObjectName(QString::fromUtf8("graphicsView_8"));
    graphicsView_8->setMinimumSize(QSize(571, 261));

    Grid_3By1->addWidget(graphicsView_8, 0, 0, 1, 3);

    graphicsView = new QGraphicsView(layoutWidget1);
    graphicsView->setObjectName(QString::fromUtf8("graphicsView"));
    graphicsView->setMinimumSize(QSize(191, 171));

    Grid_3By1->addWidget(graphicsView, 1, 0, 1, 1);

    graphicsView_4 = new QGraphicsView(layoutWidget1);
    graphicsView_4->setObjectName(QString::fromUtf8("graphicsView_4"));
    graphicsView_4->setMinimumSize(QSize(191, 171));

    Grid_3By1->addWidget(graphicsView_4, 1, 1, 1, 1);

    graphicsView_7 = new QGraphicsView(layoutWidget1);
    graphicsView_7->setObjectName(QString::fromUtf8("graphicsView_7"));
    graphicsView_7->setMinimumSize(QSize(191, 171));

    Grid_3By1->addWidget(graphicsView_7, 1, 2, 1, 1);

    MainWindow->setCentralWidget(centralwidget);
    menubar = new QMenuBar(MainWindow);
    menubar->setObjectName(QString::fromUtf8("menubar"));
    menubar->setGeometry(QRect(0, 0, 961, 22));
    menu_File = new QMenu(menubar);
    menu_File->setObjectName(QString::fromUtf8("menu_File"));
    menu_View = new QMenu(menubar);
    menu_View->setObjectName(QString::fromUtf8("menu_View"));
    menu_Tools = new QMenu(menubar);
    menu_Tools->setObjectName(QString::fromUtf8("menu_Tools"));
    menuBitwise_Operations = new QMenu(menu_Tools);
    menuBitwise_Operations->setObjectName(QString::fromUtf8("menuBitwise_Operations"));
    menuMasking = new QMenu(menu_Tools);
    menuMasking->setObjectName(QString::fromUtf8("menuMasking"));
    menu_Filters = new QMenu(menubar);
    menu_Filters->setObjectName(QString::fromUtf8("menu_Filters"));
    menu_Help = new QMenu(menubar);
    menu_Help->setObjectName(QString::fromUtf8("menu_Help"));
    menuSelection = new QMenu(menubar);
    menuSelection->setObjectName(QString::fromUtf8("menuSelection"));
    menuRecording = new QMenu(menubar);
    menuRecording->setObjectName(QString::fromUtf8("menuRecording"));
    menuTransfer_Functions = new QMenu(menubar);
    menuTransfer_Functions->setObjectName(QString::fromUtf8("menuTransfer_Functions"));
    MainWindow->setMenuBar(menubar);
    statusbar = new QStatusBar(MainWindow);
    statusbar->setObjectName(QString::fromUtf8("statusbar"));
    statusbar->setGeometry(QRect(0, 811, 961, 21));
    MainWindow->setStatusBar(statusbar);
    dockWidget = new QDockWidget(MainWindow);
    dockWidget->setObjectName(QString::fromUtf8("dockWidget"));
    dockWidget->setGeometry(QRect(663, 22, 298, 789));
    QSizePolicy sizePolicy1(QSizePolicy::Preferred, QSizePolicy::Preferred);
    sizePolicy1.setHorizontalStretch(0);
    sizePolicy1.setVerticalStretch(0);
    sizePolicy1.setHeightForWidth(dockWidget->sizePolicy().hasHeightForWidth());
    dockWidget->setSizePolicy(sizePolicy1);
    dockWidget->setFloating(false);
    dockWidget->setAllowedAreas(Qt::LeftDockWidgetArea|Qt::RightDockWidgetArea);
    dockWidgetContents = new QWidget();
    dockWidgetContents->setObjectName(QString::fromUtf8("dockWidgetContents"));
    dockWidgetContents->setGeometry(QRect(0, 22, 298, 767));
    horizontalLayout = new QHBoxLayout(dockWidgetContents);
    horizontalLayout->setSpacing(6);
    horizontalLayout->setMargin(0);
    horizontalLayout->setObjectName(QString::fromUtf8("horizontalLayout"));
    tab_widget = new QTabWidget(dockWidgetContents);
    tab_widget->setObjectName(QString::fromUtf8("tab_widget"));
    tab_widget->setMinimumSize(QSize(280, 734));
    tab_widget->setTabShape(QTabWidget::Rounded);
    history_tab = new QWidget();
    history_tab->setObjectName(QString::fromUtf8("history_tab"));
    history_tab->setGeometry(QRect(0, 0, 274, 722));
    gridLayout = new QGridLayout(history_tab);
    gridLayout->setSpacing(6);
    gridLayout->setMargin(0);
    gridLayout->setObjectName(QString::fromUtf8("gridLayout"));
    listWidget = new QListWidget(history_tab);
    listWidget->setObjectName(QString::fromUtf8("listWidget"));

    gridLayout->addWidget(listWidget, 0, 0, 1, 2);

    pushButton_3 = new QPushButton(history_tab);
    pushButton_3->setObjectName(QString::fromUtf8("pushButton_3"));

    gridLayout->addWidget(pushButton_3, 1, 0, 1, 1);

    pushButton_4 = new QPushButton(history_tab);
    pushButton_4->setObjectName(QString::fromUtf8("pushButton_4"));

    gridLayout->addWidget(pushButton_4, 1, 1, 1, 1);

    tab_widget->addTab(history_tab, QString());
    tools_tab = new QWidget();
    tools_tab->setObjectName(QString::fromUtf8("tools_tab"));
    tools_tab->setGeometry(QRect(0, 0, 274, 722));
    polyline_tool_widget = new QWidget(tools_tab);
    polyline_tool_widget->setObjectName(QString::fromUtf8("polyline_tool_widget"));
    polyline_tool_widget->setEnabled(true);
    polyline_tool_widget->setGeometry(QRect(0, 0, 271, 531));
    polyline_tool_widget->setMinimumSize(QSize(271, 531));
    label_7 = new QLabel(polyline_tool_widget);
    label_7->setObjectName(QString::fromUtf8("label_7"));
    label_7->setGeometry(QRect(90, 10, 71, 16));
    QFont font;
    font.setBold(true);
    font.setWeight(75);
    label_7->setFont(font);
    checkBox = new QCheckBox(polyline_tool_widget);
    checkBox->setObjectName(QString::fromUtf8("checkBox"));
    checkBox->setGeometry(QRect(20, 30, 91, 18));
    checkBox->setLayoutDirection(Qt::RightToLeft);
    toolButton = new QToolButton(polyline_tool_widget);
    toolButton->setObjectName(QString::fromUtf8("toolButton"));
    toolButton->setGeometry(QRect(40, 80, 161, 20));
    toolButton_2 = new QToolButton(polyline_tool_widget);
    toolButton_2->setObjectName(QString::fromUtf8("toolButton_2"));
    toolButton_2->setGeometry(QRect(40, 110, 161, 20));
    toolButton_3 = new QToolButton(polyline_tool_widget);
    toolButton_3->setObjectName(QString::fromUtf8("toolButton_3"));
    toolButton_3->setGeometry(QRect(40, 140, 161, 20));
    toolButton_4 = new QToolButton(polyline_tool_widget);
    toolButton_4->setObjectName(QString::fromUtf8("toolButton_4"));
    toolButton_4->setGeometry(QRect(40, 170, 161, 20));
    checkBox_3 = new QCheckBox(polyline_tool_widget);
    checkBox_3->setObjectName(QString::fromUtf8("checkBox_3"));
    checkBox_3->setGeometry(QRect(40, 50, 72, 18));
    checkBox_3->setLayoutDirection(Qt::RightToLeft);
    polyline_close_Button = new QToolButton(polyline_tool_widget);
    polyline_close_Button->setObjectName(QString::fromUtf8("polyline_close_Button"));
    polyline_close_Button->setGeometry(QRect(40, 200, 161, 20));
    Cursor_information_widget = new QWidget(tools_tab);
    Cursor_information_widget->setObjectName(QString::fromUtf8("Cursor_information_widget"));
    Cursor_information_widget->setGeometry(QRect(0, 530, 281, 181));
    Cursor_information_widget->setMinimumSize(QSize(281, 181));
    label_2 = new QLabel(Cursor_information_widget);
    label_2->setObjectName(QString::fromUtf8("label_2"));
    label_2->setGeometry(QRect(91, 9, 121, 28));
    label_2->setFont(font);
    lcdNumber = new QLCDNumber(Cursor_information_widget);
    lcdNumber->setObjectName(QString::fromUtf8("lcdNumber"));
    lcdNumber->setGeometry(QRect(144, 43, 81, 28));
    lcdNumber_2 = new QLCDNumber(Cursor_information_widget);
    lcdNumber_2->setObjectName(QString::fromUtf8("lcdNumber_2"));
    lcdNumber_2->setGeometry(QRect(144, 77, 81, 27));
    lcdNumber_3 = new QLCDNumber(Cursor_information_widget);
    lcdNumber_3->setObjectName(QString::fromUtf8("lcdNumber_3"));
    lcdNumber_3->setGeometry(QRect(144, 110, 81, 28));
    lcdNumber_4 = new QLCDNumber(Cursor_information_widget);
    lcdNumber_4->setObjectName(QString::fromUtf8("lcdNumber_4"));
    lcdNumber_4->setGeometry(QRect(144, 144, 81, 28));
    label_3 = new QLabel(Cursor_information_widget);
    label_3->setObjectName(QString::fromUtf8("label_3"));
    label_3->setGeometry(QRect(57, 43, 81, 28));
    label_4 = new QLabel(Cursor_information_widget);
    label_4->setObjectName(QString::fromUtf8("label_4"));
    label_4->setGeometry(QRect(57, 77, 81, 27));
    label_6 = new QLabel(Cursor_information_widget);
    label_6->setObjectName(QString::fromUtf8("label_6"));
    label_6->setGeometry(QRect(57, 110, 81, 28));
    label_5 = new QLabel(Cursor_information_widget);
    label_5->setObjectName(QString::fromUtf8("label_5"));
    label_5->setGeometry(QRect(57, 144, 81, 28));
    paintbrush_tool_widget = new QWidget(tools_tab);
    paintbrush_tool_widget->setObjectName(QString::fromUtf8("paintbrush_tool_widget"));
    paintbrush_tool_widget->setGeometry(QRect(0, 0, 271, 531));
    paintbrush_tool_widget->setMinimumSize(QSize(271, 531));
    label_8 = new QLabel(paintbrush_tool_widget);
    label_8->setObjectName(QString::fromUtf8("label_8"));
    label_8->setGeometry(QRect(90, 10, 71, 16));
    label_8->setFont(font);
    checkBox_2 = new QCheckBox(paintbrush_tool_widget);
    checkBox_2->setObjectName(QString::fromUtf8("checkBox_2"));
    checkBox_2->setGeometry(QRect(40, 70, 81, 20));
    checkBox_2->setLayoutDirection(Qt::RightToLeft);
    toolButton_5 = new QToolButton(paintbrush_tool_widget);
    toolButton_5->setObjectName(QString::fromUtf8("toolButton_5"));
    toolButton_5->setGeometry(QRect(40, 100, 161, 20));
    toolButton_6 = new QToolButton(paintbrush_tool_widget);
    toolButton_6->setObjectName(QString::fromUtf8("toolButton_6"));
    toolButton_6->setGeometry(QRect(40, 130, 161, 20));
    Paintbrush_close_Button = new QToolButton(paintbrush_tool_widget);
    Paintbrush_close_Button->setObjectName(QString::fromUtf8("Paintbrush_close_Button"));
    Paintbrush_close_Button->setGeometry(QRect(40, 160, 161, 20));
    label_9 = new QLabel(paintbrush_tool_widget);
    label_9->setObjectName(QString::fromUtf8("label_9"));
    label_9->setGeometry(QRect(40, 40, 71, 16));
    spinBox = new QSpinBox(paintbrush_tool_widget);
    spinBox->setObjectName(QString::fromUtf8("spinBox"));
    spinBox->setGeometry(QRect(140, 40, 51, 22));
    spinBox->setMinimum(1);
    spinBox->setValue(5);
    resample_tool_widget = new QWidget(tools_tab);
    resample_tool_widget->setObjectName(QString::fromUtf8("resample_tool_widget"));
    resample_tool_widget->setGeometry(QRect(0, 0, 271, 531));
    resample_tool_widget->setMinimumSize(QSize(271, 531));
    label_15 = new QLabel(resample_tool_widget);
    label_15->setObjectName(QString::fromUtf8("label_15"));
    label_15->setGeometry(QRect(58, 30, 16, 17));
    spinBox_5 = new QSpinBox(resample_tool_widget);
    spinBox_5->setObjectName(QString::fromUtf8("spinBox_5"));
    spinBox_5->setGeometry(QRect(120, 30, 91, 20));
    spinBox_5->setMinimum(1);
    spinBox_5->setMaximum(512);
    spinBox_5->setValue(128);
    spinBox_6 = new QSpinBox(resample_tool_widget);
    spinBox_6->setObjectName(QString::fromUtf8("spinBox_6"));
    spinBox_6->setGeometry(QRect(120, 56, 91, 20));
    spinBox_6->setMinimum(1);
    spinBox_6->setMaximum(512);
    spinBox_6->setValue(128);
    label_16 = new QLabel(resample_tool_widget);
    label_16->setObjectName(QString::fromUtf8("label_16"));
    label_16->setGeometry(QRect(58, 56, 16, 17));
    spinBox_7 = new QSpinBox(resample_tool_widget);
    spinBox_7->setObjectName(QString::fromUtf8("spinBox_7"));
    spinBox_7->setGeometry(QRect(120, 82, 91, 20));
    spinBox_7->setMinimum(1);
    spinBox_7->setMaximum(512);
    spinBox_7->setValue(128);
    label_17 = new QLabel(resample_tool_widget);
    label_17->setObjectName(QString::fromUtf8("label_17"));
    label_17->setGeometry(QRect(58, 82, 16, 17));
    label_18 = new QLabel(resample_tool_widget);
    label_18->setObjectName(QString::fromUtf8("label_18"));
    label_18->setGeometry(QRect(58, 108, 28, 17));
    comboBox_2 = new QComboBox(resample_tool_widget);
    comboBox_2->setObjectName(QString::fromUtf8("comboBox_2"));
    comboBox_2->setGeometry(QRect(120, 108, 91, 20));
    label_10 = new QLabel(resample_tool_widget);
    label_10->setObjectName(QString::fromUtf8("label_10"));
    label_10->setGeometry(QRect(90, 10, 56, 16));
    label_10->setFont(font);
    resample_close_Button = new QToolButton(resample_tool_widget);
    resample_close_Button->setObjectName(QString::fromUtf8("resample_close_Button"));
    resample_close_Button->setGeometry(QRect(140, 130, 91, 20));
    toolButton_14 = new QToolButton(resample_tool_widget);
    toolButton_14->setObjectName(QString::fromUtf8("toolButton_14"));
    toolButton_14->setGeometry(QRect(40, 130, 91, 20));
    crop_tool_widget = new QWidget(tools_tab);
    crop_tool_widget->setObjectName(QString::fromUtf8("crop_tool_widget"));
    crop_tool_widget->setGeometry(QRect(0, 0, 271, 531));
    crop_tool_widget->setMinimumSize(QSize(271, 531));
    crop_close_Button = new QToolButton(crop_tool_widget);
    crop_close_Button->setObjectName(QString::fromUtf8("crop_close_Button"));
    crop_close_Button->setGeometry(QRect(150, 230, 71, 20));
    toolButton_29 = new QToolButton(crop_tool_widget);
    toolButton_29->setObjectName(QString::fromUtf8("toolButton_29"));
    toolButton_29->setGeometry(QRect(60, 230, 71, 20));
    label_28 = new QLabel(crop_tool_widget);
    label_28->setObjectName(QString::fromUtf8("label_28"));
    label_28->setGeometry(QRect(77, 40, 29, 17));
    lcdNumber_5 = new QLCDNumber(crop_tool_widget);
    lcdNumber_5->setObjectName(QString::fromUtf8("lcdNumber_5"));
    lcdNumber_5->setGeometry(QRect(120, 40, 71, 23));
    label_27 = new QLabel(crop_tool_widget);
    label_27->setObjectName(QString::fromUtf8("label_27"));
    label_27->setGeometry(QRect(110, 10, 31, 16));
    label_27->setFont(font);
    label_29 = new QLabel(crop_tool_widget);
    label_29->setObjectName(QString::fromUtf8("label_29"));
    label_29->setGeometry(QRect(77, 70, 29, 17));
    lcdNumber_6 = new QLCDNumber(crop_tool_widget);
    lcdNumber_6->setObjectName(QString::fromUtf8("lcdNumber_6"));
    lcdNumber_6->setGeometry(QRect(120, 70, 71, 23));
    label_30 = new QLabel(crop_tool_widget);
    label_30->setObjectName(QString::fromUtf8("label_30"));
    label_30->setGeometry(QRect(77, 100, 29, 17));
    lcdNumber_7 = new QLCDNumber(crop_tool_widget);
    lcdNumber_7->setObjectName(QString::fromUtf8("lcdNumber_7"));
    lcdNumber_7->setGeometry(QRect(120, 100, 71, 23));
    lcdNumber_8 = new QLCDNumber(crop_tool_widget);
    lcdNumber_8->setObjectName(QString::fromUtf8("lcdNumber_8"));
    lcdNumber_8->setGeometry(QRect(120, 130, 71, 23));
    label_31 = new QLabel(crop_tool_widget);
    label_31->setObjectName(QString::fromUtf8("label_31"));
    label_31->setGeometry(QRect(77, 130, 29, 17));
    label_32 = new QLabel(crop_tool_widget);
    label_32->setObjectName(QString::fromUtf8("label_32"));
    label_32->setGeometry(QRect(77, 160, 29, 17));
    lcdNumber_9 = new QLCDNumber(crop_tool_widget);
    lcdNumber_9->setObjectName(QString::fromUtf8("lcdNumber_9"));
    lcdNumber_9->setGeometry(QRect(120, 160, 71, 23));
    label_33 = new QLabel(crop_tool_widget);
    label_33->setObjectName(QString::fromUtf8("label_33"));
    label_33->setGeometry(QRect(77, 190, 29, 17));
    lcdNumber_10 = new QLCDNumber(crop_tool_widget);
    lcdNumber_10->setObjectName(QString::fromUtf8("lcdNumber_10"));
    lcdNumber_10->setGeometry(QRect(120, 190, 71, 23));
    tab_widget->addTab(tools_tab, QString());
    Filter_tab = new QWidget();
    Filter_tab->setObjectName(QString::fromUtf8("Filter_tab"));
    Filter_tab->setGeometry(QRect(0, 0, 274, 722));
    Gaussian_filter_widget = new QWidget(Filter_tab);
    Gaussian_filter_widget->setObjectName(QString::fromUtf8("Gaussian_filter_widget"));
    Gaussian_filter_widget->setGeometry(QRect(0, 0, 271, 531));
    Gaussian_filter_widget->setMinimumSize(QSize(271, 531));
    label_21 = new QLabel(Gaussian_filter_widget);
    label_21->setObjectName(QString::fromUtf8("label_21"));
    label_21->setGeometry(QRect(100, 10, 61, 20));
    label_21->setFont(font);
    guassian_close_Button = new QToolButton(Gaussian_filter_widget);
    guassian_close_Button->setObjectName(QString::fromUtf8("guassian_close_Button"));
    guassian_close_Button->setGeometry(QRect(138, 90, 81, 20));
    toolButton_25 = new QToolButton(Gaussian_filter_widget);
    toolButton_25->setObjectName(QString::fromUtf8("toolButton_25"));
    toolButton_25->setGeometry(QRect(20, 90, 81, 20));
    label_22 = new QLabel(Gaussian_filter_widget);
    label_22->setObjectName(QString::fromUtf8("label_22"));
    label_22->setGeometry(QRect(20, 40, 44, 17));
    spinBox_10 = new QSpinBox(Gaussian_filter_widget);
    spinBox_10->setObjectName(QString::fromUtf8("spinBox_10"));
    spinBox_10->setGeometry(QRect(91, 35, 101, 20));
    spinBox_10->setMinimum(1);
    spinBox_10->setValue(1);
    spinBox_11 = new QSpinBox(Gaussian_filter_widget);
    spinBox_11->setObjectName(QString::fromUtf8("spinBox_11"));
    spinBox_11->setGeometry(QRect(91, 55, 101, 20));
    spinBox_11->setMinimum(1);
    spinBox_11->setMaximum(200);
    spinBox_11->setValue(20);
    label_24 = new QLabel(Gaussian_filter_widget);
    label_24->setObjectName(QString::fromUtf8("label_24"));
    label_24->setGeometry(QRect(30, 60, 34, 16));
    Median_filter_widget = new QWidget(Filter_tab);
    Median_filter_widget->setObjectName(QString::fromUtf8("Median_filter_widget"));
    Median_filter_widget->setGeometry(QRect(0, 0, 271, 531));
    Median_filter_widget->setMinimumSize(QSize(271, 531));
    label_25 = new QLabel(Median_filter_widget);
    label_25->setObjectName(QString::fromUtf8("label_25"));
    label_25->setGeometry(QRect(100, 10, 61, 20));
    label_25->setFont(font);
    median_close_Button = new QToolButton(Median_filter_widget);
    median_close_Button->setObjectName(QString::fromUtf8("median_close_Button"));
    median_close_Button->setGeometry(QRect(140, 70, 81, 20));
    toolButton_27 = new QToolButton(Median_filter_widget);
    toolButton_27->setObjectName(QString::fromUtf8("toolButton_27"));
    toolButton_27->setGeometry(QRect(20, 70, 81, 20));
    label_26 = new QLabel(Median_filter_widget);
    label_26->setObjectName(QString::fromUtf8("label_26"));
    label_26->setGeometry(QRect(20, 40, 44, 17));
    spinBox_12 = new QSpinBox(Median_filter_widget);
    spinBox_12->setObjectName(QString::fromUtf8("spinBox_12"));
    spinBox_12->setGeometry(QRect(91, 35, 101, 20));
    spinBox_12->setMinimum(1);
    spinBox_12->setValue(1);
    Histogram_filter_widget = new QWidget(Filter_tab);
    Histogram_filter_widget->setObjectName(QString::fromUtf8("Histogram_filter_widget"));
    Histogram_filter_widget->setGeometry(QRect(0, 0, 271, 531));
    Histogram_filter_widget->setMinimumSize(QSize(271, 531));
    label_19 = new QLabel(Histogram_filter_widget);
    label_19->setObjectName(QString::fromUtf8("label_19"));
    label_19->setGeometry(QRect(30, 30, 58, 17));
    spinBox_8 = new QSpinBox(Histogram_filter_widget);
    spinBox_8->setObjectName(QString::fromUtf8("spinBox_8"));
    spinBox_8->setGeometry(QRect(95, 30, 101, 20));
    spinBox_8->setMinimum(1);
    spinBox_8->setMaximum(512);
    spinBox_8->setValue(128);
    spinBox_9 = new QSpinBox(Histogram_filter_widget);
    spinBox_9->setObjectName(QString::fromUtf8("spinBox_9"));
    spinBox_9->setGeometry(QRect(95, 56, 101, 20));
    spinBox_9->setMinimum(1);
    spinBox_9->setMaximum(512);
    spinBox_9->setValue(128);
    label_20 = new QLabel(Histogram_filter_widget);
    label_20->setObjectName(QString::fromUtf8("label_20"));
    label_20->setGeometry(QRect(30, 56, 31, 17));
    label_23 = new QLabel(Histogram_filter_widget);
    label_23->setObjectName(QString::fromUtf8("label_23"));
    label_23->setGeometry(QRect(90, 10, 59, 16));
    label_23->setFont(font);
    toolButton_12 = new QToolButton(Histogram_filter_widget);
    toolButton_12->setObjectName(QString::fromUtf8("toolButton_12"));
    toolButton_12->setGeometry(QRect(9, 91, 91, 20));
    histogram_close_Button = new QToolButton(Histogram_filter_widget);
    histogram_close_Button->setObjectName(QString::fromUtf8("histogram_close_Button"));
    histogram_close_Button->setGeometry(QRect(120, 90, 91, 20));
    tab_widget->addTab(Filter_tab, QString());
    Recorder_tab = new QWidget();
    Recorder_tab->setObjectName(QString::fromUtf8("Recorder_tab"));
    Recorder_tab->setGeometry(QRect(0, 0, 274, 722));
    verticalLayout_2 = new QVBoxLayout(Recorder_tab);
    verticalLayout_2->setSpacing(6);
    verticalLayout_2->setMargin(0);
    verticalLayout_2->setObjectName(QString::fromUtf8("verticalLayout_2"));
    groupBox = new QGroupBox(Recorder_tab);
    groupBox->setObjectName(QString::fromUtf8("groupBox"));
    groupBox->setMinimumSize(QSize(0, 51));
    groupBox->setMaximumSize(QSize(16777215, 51));
    groupBox->setFlat(false);
    pushButton_5 = new QPushButton(groupBox);
    pushButton_5->setObjectName(QString::fromUtf8("pushButton_5"));
    pushButton_5->setGeometry(QRect(10, 20, 75, 23));
    pushButton_6 = new QPushButton(groupBox);
    pushButton_6->setObjectName(QString::fromUtf8("pushButton_6"));
    pushButton_6->setGeometry(QRect(100, 20, 75, 23));

    verticalLayout_2->addWidget(groupBox);

    groupBox_2 = new QGroupBox(Recorder_tab);
    groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
    pushButton_7 = new QPushButton(groupBox_2);
    pushButton_7->setObjectName(QString::fromUtf8("pushButton_7"));
    pushButton_7->setGeometry(QRect(10, 20, 181, 23));
    pushButton_8 = new QPushButton(groupBox_2);
    pushButton_8->setObjectName(QString::fromUtf8("pushButton_8"));
    pushButton_8->setGeometry(QRect(10, 80, 181, 23));
    pushButton_9 = new QPushButton(groupBox_2);
    pushButton_9->setObjectName(QString::fromUtf8("pushButton_9"));
    pushButton_9->setGeometry(QRect(10, 50, 181, 23));
    pushButton_10 = new QPushButton(groupBox_2);
    pushButton_10->setObjectName(QString::fromUtf8("pushButton_10"));
    pushButton_10->setGeometry(QRect(10, 130, 181, 23));
    label = new QLabel(groupBox_2);
    label->setObjectName(QString::fromUtf8("label"));
    label->setGeometry(QRect(10, 110, 61, 16));
    pushButton_11 = new QPushButton(groupBox_2);
    pushButton_11->setObjectName(QString::fromUtf8("pushButton_11"));
    pushButton_11->setGeometry(QRect(10, 170, 181, 23));
    pushButton_12 = new QPushButton(groupBox_2);
    pushButton_12->setObjectName(QString::fromUtf8("pushButton_12"));
    pushButton_12->setGeometry(QRect(10, 200, 181, 23));
    pushButton_13 = new QPushButton(groupBox_2);
    pushButton_13->setObjectName(QString::fromUtf8("pushButton_13"));
    pushButton_13->setGeometry(QRect(10, 240, 181, 23));

    verticalLayout_2->addWidget(groupBox_2);

    tab_widget->addTab(Recorder_tab, QString());

    horizontalLayout->addWidget(tab_widget);

    dockWidget->setWidget(dockWidgetContents);
    MainWindow->addDockWidget(static_cast<Qt::DockWidgetArea>(2), dockWidget);

    menubar->addAction(menu_File->menuAction());
    menubar->addAction(menuSelection->menuAction());
    menubar->addAction(menu_View->menuAction());
    menubar->addAction(menu_Tools->menuAction());
    menubar->addAction(menu_Filters->menuAction());
    menubar->addAction(menuRecording->menuAction());
    menubar->addAction(menu_Help->menuAction());
    menubar->addAction(menuTransfer_Functions->menuAction());
    menu_File->addAction(actionCreate_New_Project);
    menu_File->addAction(actionOpen_Existing_Project);
    menu_File->addAction(actionLast_Used_Projects);
    menu_File->addAction(actionSave_Current_Project);
    menu_File->addAction(actionClose_Project);
    menu_File->addSeparator();
    menu_File->addAction(actionLoad_Dataset);
    menu_File->addAction(actionSave_Dataset);
    menu_File->addAction(actionClose_Dataset);
    menu_File->addSeparator();
    menu_File->addAction(actionQuit);
    menu_View->addAction(actionGo_Fullscreen);
    menu_View->addSeparator();
    menu_View->addAction(action2_x_2_View);
    menu_View->addAction(action1_x_3_Viw);
    menu_View->addAction(actionSinge_View);
    menu_View->addSeparator();
    menu_View->addAction(actionDirect_Volume_Rendering);
    menu_View->addAction(actionIsosurface_Rendering);
    menu_View->addAction(actionStereo_Projection);
    menu_Tools->addAction(actionCrop);
    menu_Tools->addAction(menuBitwise_Operations->menuAction());
    menu_Tools->addAction(menuMasking->menuAction());
    menu_Tools->addAction(actionPaint_brush);
    menu_Tools->addAction(actionInformation);
    menu_Tools->addAction(actionInvert);
    menu_Tools->addAction(actionResample);
    menuBitwise_Operations->addAction(actionAnd);
    menuBitwise_Operations->addAction(actionOr);
    menuBitwise_Operations->addAction(actionNot);
    menuBitwise_Operations->addAction(actionXor);
    menuMasking->addAction(actionIsosurface);
    menuMasking->addAction(actionGeneric);
    menu_Filters->addAction(actionMedian);
    menu_Filters->addSeparator();
    menu_Filters->addAction(actionGaussian);
    menu_Filters->addAction(actionEdge_Detection);
    menu_Filters->addSeparator();
    menu_Filters->addAction(actionDesign_Convolution);
    menu_Filters->addAction(actionLoad_Convolution);
    menu_Filters->addAction(actionSave_Convolution);
    menu_Filters->addAction(actionHistogram);
    menu_Help->addAction(actionAbout);
    menu_Help->addAction(actionOpen_Online_Help);
    menuSelection->addAction(actionBox);
    menuSelection->addAction(actionPoly_Line);
    menuSelection->addAction(actionSelect_All);
    menuSelection->addSeparator();
    menuSelection->addAction(actionDelete_Selection);
    menuSelection->addAction(actionInvert_Selection);
    menuSelection->addSeparator();
    menuSelection->addAction(actionStastistcs);
    menuSelection->addSeparator();
    menuSelection->addAction(actionUndo);
    menuSelection->addAction(actionRedo);
    menuRecording->addAction(actionREcord_Image);
    menuRecording->addAction(actionRecord_Movie);
    menuTransfer_Functions->addAction(actionLoad);
    menuTransfer_Functions->addAction(actionSave);
    menuTransfer_Functions->addSeparator();
    menuTransfer_Functions->addAction(action1D_Transfer_Function_Editor);
    menuTransfer_Functions->addAction(action2D_Transfer_Function_Editor);
    menuTransfer_Functions->addSeparator();
    menuTransfer_Functions->addAction(actionToggle_between_1D_and_2D);

    retranslateUi(MainWindow);
    QObject::connect(actionPaint_brush, SIGNAL(triggered()), paintbrush_tool_widget, SLOT(show()));
    QObject::connect(actionCrop, SIGNAL(triggered()), crop_tool_widget, SLOT(show()));
    QObject::connect(actionPoly_Line, SIGNAL(triggered()), polyline_tool_widget, SLOT(show()));
    QObject::connect(actionGaussian, SIGNAL(triggered()), Gaussian_filter_widget, SLOT(show()));
    QObject::connect(actionHistogram, SIGNAL(triggered()), Histogram_filter_widget, SLOT(show()));
    QObject::connect(actionResample, SIGNAL(triggered()), resample_tool_widget, SLOT(show()));
    QObject::connect(median_close_Button, SIGNAL(clicked()), Median_filter_widget, SLOT(hide()));
    QObject::connect(Paintbrush_close_Button, SIGNAL(clicked()), paintbrush_tool_widget, SLOT(hide()));
    QObject::connect(polyline_close_Button, SIGNAL(clicked()), polyline_tool_widget, SLOT(hide()));
    QObject::connect(crop_close_Button, SIGNAL(clicked()), crop_tool_widget, SLOT(hide()));
    QObject::connect(guassian_close_Button, SIGNAL(clicked()), Gaussian_filter_widget, SLOT(hide()));
    QObject::connect(histogram_close_Button, SIGNAL(clicked()), Histogram_filter_widget, SLOT(hide()));
    QObject::connect(resample_close_Button, SIGNAL(clicked()), resample_tool_widget, SLOT(hide()));
    QObject::connect(actionMedian, SIGNAL(triggered()), Median_filter_widget, SLOT(show()));
    QObject::connect(action2_x_2_View, SIGNAL(triggered()), widget_2By2, SLOT(show()));
    QObject::connect(action2_x_2_View, SIGNAL(triggered()), widget_3By1, SLOT(hide()));
    QObject::connect(action2_x_2_View, SIGNAL(triggered()), widget_Single, SLOT(hide()));
    QObject::connect(action1_x_3_Viw, SIGNAL(triggered()), widget_3By1, SLOT(show()));
    QObject::connect(action1_x_3_Viw, SIGNAL(triggered()), widget_2By2, SLOT(hide()));
    QObject::connect(action1_x_3_Viw, SIGNAL(triggered()), widget_Single, SLOT(hide()));
    QObject::connect(actionSinge_View, SIGNAL(triggered()), widget_Single, SLOT(show()));
    QObject::connect(actionSinge_View, SIGNAL(triggered()), widget_3By1, SLOT(hide()));
    QObject::connect(actionSinge_View, SIGNAL(triggered()), widget_2By2, SLOT(hide()));
    QObject::connect(actionQuit, SIGNAL(triggered()), MainWindow, SLOT(close()));
    QObject::connect(action1D_Transfer_Function_Editor, SIGNAL(triggered()), MainWindow, SLOT(Show1DTransferFunction()));
    QObject::connect(action2D_Transfer_Function_Editor, SIGNAL(triggered()), MainWindow, SLOT(Show2DTransferFunction()));

    tab_widget->setCurrentIndex(1);


    QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
    MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", 0, QApplication::UnicodeUTF8));
    actionWerwer->setText(QApplication::translate("MainWindow", "werwer", 0, QApplication::UnicodeUTF8));
    actionCreate_New_Project->setText(QApplication::translate("MainWindow", "Create New Project", 0, QApplication::UnicodeUTF8));
    actionOpen_Existing_Project->setText(QApplication::translate("MainWindow", "Open Existing Project", 0, QApplication::UnicodeUTF8));
    actionLast_Used_Projects->setText(QApplication::translate("MainWindow", "Last Used Projects", 0, QApplication::UnicodeUTF8));
    actionSave_Current_Project->setText(QApplication::translate("MainWindow", "Save Current Project", 0, QApplication::UnicodeUTF8));
    actionLoad_Dataset->setText(QApplication::translate("MainWindow", "Load Dataset", 0, QApplication::UnicodeUTF8));
    actionSave_Dataset->setText(QApplication::translate("MainWindow", "Save Dataset", 0, QApplication::UnicodeUTF8));
    actionQuit->setText(QApplication::translate("MainWindow", "Quit", 0, QApplication::UnicodeUTF8));
    actionClose_Dataset->setText(QApplication::translate("MainWindow", "Close Dataset", 0, QApplication::UnicodeUTF8));
    actionClose_Project->setText(QApplication::translate("MainWindow", "Close Project", 0, QApplication::UnicodeUTF8));
    action2_x_2_View->setText(QApplication::translate("MainWindow", "2 x 2 View", 0, QApplication::UnicodeUTF8));
    action1_x_3_Viw->setText(QApplication::translate("MainWindow", "1 x 3 View", 0, QApplication::UnicodeUTF8));
    actionSinge_View->setText(QApplication::translate("MainWindow", "Single View", 0, QApplication::UnicodeUTF8));
    actionDirect_Volume_Rendering->setText(QApplication::translate("MainWindow", "Direct Volume Rendering", 0, QApplication::UnicodeUTF8));
    actionIsosurface_Rendering->setText(QApplication::translate("MainWindow", "Isosurface Rendering", 0, QApplication::UnicodeUTF8));
    actionCrop->setText(QApplication::translate("MainWindow", "Crop", 0, QApplication::UnicodeUTF8));
    actionMask->setText(QApplication::translate("MainWindow", "Mask", 0, QApplication::UnicodeUTF8));
    actionBox->setText(QApplication::translate("MainWindow", "Box Select", 0, QApplication::UnicodeUTF8));
    actionPoly_Line->setText(QApplication::translate("MainWindow", "Poly Line Select", 0, QApplication::UnicodeUTF8));
    actionSelect_All->setText(QApplication::translate("MainWindow", "Select All", 0, QApplication::UnicodeUTF8));
    actionDelete_Selection->setText(QApplication::translate("MainWindow", "Delete Selection", 0, QApplication::UnicodeUTF8));
    actionInvert_Selection->setText(QApplication::translate("MainWindow", "Invert Selection", 0, QApplication::UnicodeUTF8));
    actionHistorgram->setText(QApplication::translate("MainWindow", "Historgram", 0, QApplication::UnicodeUTF8));
    actionStastistcs->setText(QApplication::translate("MainWindow", "Stastistcs", 0, QApplication::UnicodeUTF8));
    actionUndo->setText(QApplication::translate("MainWindow", "Undo", 0, QApplication::UnicodeUTF8));
    actionRedo->setText(QApplication::translate("MainWindow", "Redo", 0, QApplication::UnicodeUTF8));
    actionGenerate_Movie->setText(QApplication::translate("MainWindow", "Generate Movie", 0, QApplication::UnicodeUTF8));
    actionREcord_Image->setText(QApplication::translate("MainWindow", "Record Image", 0, QApplication::UnicodeUTF8));
    actionGo_Fullscreen->setText(QApplication::translate("MainWindow", "Go Fullscreen", 0, QApplication::UnicodeUTF8));
    actionRecord_Movie->setText(QApplication::translate("MainWindow", "Record Movie", 0, QApplication::UnicodeUTF8));
    actionMedian->setText(QApplication::translate("MainWindow", "Median", 0, QApplication::UnicodeUTF8));
    actionGaussian->setText(QApplication::translate("MainWindow", "Gaussian", 0, QApplication::UnicodeUTF8));
    actionEdge_Detection->setText(QApplication::translate("MainWindow", "Edge Detection", 0, QApplication::UnicodeUTF8));
    actionDesign_Convolution->setText(QApplication::translate("MainWindow", "Design Convolution", 0, QApplication::UnicodeUTF8));
    actionLoad_Convolution->setText(QApplication::translate("MainWindow", "Load Convolution", 0, QApplication::UnicodeUTF8));
    actionSave_Convolution->setText(QApplication::translate("MainWindow", "Save Convolution", 0, QApplication::UnicodeUTF8));
    actionAnd->setText(QApplication::translate("MainWindow", "and", 0, QApplication::UnicodeUTF8));
    actionOr->setText(QApplication::translate("MainWindow", "or", 0, QApplication::UnicodeUTF8));
    actionNot->setText(QApplication::translate("MainWindow", "not", 0, QApplication::UnicodeUTF8));
    actionXor->setText(QApplication::translate("MainWindow", "xor", 0, QApplication::UnicodeUTF8));
    actionLoad_Transfer_Function->setText(QApplication::translate("MainWindow", "Load Transfer Function", 0, QApplication::UnicodeUTF8));
    actionAbout->setText(QApplication::translate("MainWindow", "About", 0, QApplication::UnicodeUTF8));
    actionOpen_Online_Help->setText(QApplication::translate("MainWindow", "Open Online Help", 0, QApplication::UnicodeUTF8));
    actionLoad->setText(QApplication::translate("MainWindow", "Load", 0, QApplication::UnicodeUTF8));
    actionSave->setText(QApplication::translate("MainWindow", "Save Current", 0, QApplication::UnicodeUTF8));
    action1D_Transfer_Function_Editor->setText(QApplication::translate("MainWindow", "1D Transfer Function Editor", 0, QApplication::UnicodeUTF8));
    action2D_Transfer_Function_Editor->setText(QApplication::translate("MainWindow", "2D Transfer Function Editor", 0, QApplication::UnicodeUTF8));
    actionToggle_between_1D_and_2D->setText(QApplication::translate("MainWindow", "Toggle between 1D and 2D", 0, QApplication::UnicodeUTF8));
    actionStereo_Projection->setText(QApplication::translate("MainWindow", "Stereo Projection", 0, QApplication::UnicodeUTF8));
    actionIsosurface->setText(QApplication::translate("MainWindow", "Isosurface", 0, QApplication::UnicodeUTF8));
    actionPoly_line->setText(QApplication::translate("MainWindow", "Poly-line", 0, QApplication::UnicodeUTF8));
    actionPaint_brush->setText(QApplication::translate("MainWindow", "paint brush", 0, QApplication::UnicodeUTF8));
    actionInformation->setText(QApplication::translate("MainWindow", "Information", 0, QApplication::UnicodeUTF8));
    actionInvert->setText(QApplication::translate("MainWindow", "Invert", 0, QApplication::UnicodeUTF8));
    actionGeneric->setText(QApplication::translate("MainWindow", "Generic", 0, QApplication::UnicodeUTF8));
    actionResample->setText(QApplication::translate("MainWindow", "Resample", 0, QApplication::UnicodeUTF8));
    actionHistogram->setText(QApplication::translate("MainWindow", "Histogram", 0, QApplication::UnicodeUTF8));
    menu_File->setTitle(QApplication::translate("MainWindow", "&File", 0, QApplication::UnicodeUTF8));
    menu_View->setTitle(QApplication::translate("MainWindow", "&View", 0, QApplication::UnicodeUTF8));
    menu_Tools->setTitle(QApplication::translate("MainWindow", "&Tools", 0, QApplication::UnicodeUTF8));
    menuBitwise_Operations->setTitle(QApplication::translate("MainWindow", "Bitwise Operations", 0, QApplication::UnicodeUTF8));
    menuMasking->setTitle(QApplication::translate("MainWindow", "Masking", 0, QApplication::UnicodeUTF8));
    menu_Filters->setTitle(QApplication::translate("MainWindow", "&Filters", 0, QApplication::UnicodeUTF8));
    menu_Help->setTitle(QApplication::translate("MainWindow", "&Help", 0, QApplication::UnicodeUTF8));
    menuSelection->setTitle(QApplication::translate("MainWindow", "Edit", 0, QApplication::UnicodeUTF8));
    menuRecording->setTitle(QApplication::translate("MainWindow", "Recording", 0, QApplication::UnicodeUTF8));
    menuTransfer_Functions->setTitle(QApplication::translate("MainWindow", "Transfer Functions", 0, QApplication::UnicodeUTF8));
    dockWidget->setWindowTitle(QApplication::translate("MainWindow", "Tools", 0, QApplication::UnicodeUTF8));
    pushButton_3->setText(QApplication::translate("MainWindow", "Undo", 0, QApplication::UnicodeUTF8));
    pushButton_4->setText(QApplication::translate("MainWindow", "Redo", 0, QApplication::UnicodeUTF8));
    tab_widget->setTabText(tab_widget->indexOf(history_tab), QApplication::translate("MainWindow", "History", 0, QApplication::UnicodeUTF8));
    label_7->setText(QApplication::translate("MainWindow", "Polyl-Line", 0, QApplication::UnicodeUTF8));
    checkBox->setText(QApplication::translate("MainWindow", "Stipple", 0, QApplication::UnicodeUTF8));
    toolButton->setText(QApplication::translate("MainWindow", "Clear Poly-line", 0, QApplication::UnicodeUTF8));
    toolButton_2->setText(QApplication::translate("MainWindow", "Fill", 0, QApplication::UnicodeUTF8));
    toolButton_3->setText(QApplication::translate("MainWindow", "Erase", 0, QApplication::UnicodeUTF8));
    toolButton_4->setText(QApplication::translate("MainWindow", "Crop", 0, QApplication::UnicodeUTF8));
    checkBox_3->setText(QApplication::translate("MainWindow", "Silhouette", 0, QApplication::UnicodeUTF8));
    polyline_close_Button->setText(QApplication::translate("MainWindow", "Close", 0, QApplication::UnicodeUTF8));
    label_2->setText(QApplication::translate("MainWindow", "Cursor Information", 0, QApplication::UnicodeUTF8));
    label_3->setText(QApplication::translate("MainWindow", "Value:", 0, QApplication::UnicodeUTF8));
    label_4->setText(QApplication::translate("MainWindow", "Position X:", 0, QApplication::UnicodeUTF8));
    label_6->setText(QApplication::translate("MainWindow", "Position Y:", 0, QApplication::UnicodeUTF8));
    label_5->setText(QApplication::translate("MainWindow", "Position Z:", 0, QApplication::UnicodeUTF8));
    label_8->setText(QApplication::translate("MainWindow", "Paint Brush", 0, QApplication::UnicodeUTF8));
    checkBox_2->setText(QApplication::translate("MainWindow", "Brush Erase", 0, QApplication::UnicodeUTF8));
    toolButton_5->setText(QApplication::translate("MainWindow", "Flood Fill", 0, QApplication::UnicodeUTF8));
    toolButton_6->setText(QApplication::translate("MainWindow", "Flood Erase", 0, QApplication::UnicodeUTF8));
    Paintbrush_close_Button->setText(QApplication::translate("MainWindow", "Close", 0, QApplication::UnicodeUTF8));
    label_9->setText(QApplication::translate("MainWindow", "Brush Radius", 0, QApplication::UnicodeUTF8));
    label_15->setText(QApplication::translate("MainWindow", "X:", 0, QApplication::UnicodeUTF8));
    label_16->setText(QApplication::translate("MainWindow", "Y:", 0, QApplication::UnicodeUTF8));
    label_17->setText(QApplication::translate("MainWindow", "Z:", 0, QApplication::UnicodeUTF8));
    label_18->setText(QApplication::translate("MainWindow", "Filter:", 0, QApplication::UnicodeUTF8));
    comboBox_2->insertItems(0, QStringList()
     << QApplication::translate("MainWindow", "Box", 0, QApplication::UnicodeUTF8)
     << QApplication::translate("MainWindow", "Tent", 0, QApplication::UnicodeUTF8)
     << QApplication::translate("MainWindow", "Cubic", 0, QApplication::UnicodeUTF8)
     << QApplication::translate("MainWindow", "Quadric", 0, QApplication::UnicodeUTF8)
     << QApplication::translate("MainWindow", "Gaussian", 0, QApplication::UnicodeUTF8)
    );
    label_10->setText(QApplication::translate("MainWindow", "Resample", 0, QApplication::UnicodeUTF8));
    resample_close_Button->setText(QApplication::translate("MainWindow", "Close", 0, QApplication::UnicodeUTF8));
    toolButton_14->setText(QApplication::translate("MainWindow", "Start", 0, QApplication::UnicodeUTF8));
    crop_close_Button->setText(QApplication::translate("MainWindow", "Close", 0, QApplication::UnicodeUTF8));
    toolButton_29->setText(QApplication::translate("MainWindow", "Crop", 0, QApplication::UnicodeUTF8));
    label_28->setText(QApplication::translate("MainWindow", "Min X:", 0, QApplication::UnicodeUTF8));
    label_27->setText(QApplication::translate("MainWindow", "Crop", 0, QApplication::UnicodeUTF8));
    label_29->setText(QApplication::translate("MainWindow", "Min Y:", 0, QApplication::UnicodeUTF8));
    label_30->setText(QApplication::translate("MainWindow", "Min Z:", 0, QApplication::UnicodeUTF8));
    label_31->setText(QApplication::translate("MainWindow", "Max X:", 0, QApplication::UnicodeUTF8));
    label_32->setText(QApplication::translate("MainWindow", "Max Y:", 0, QApplication::UnicodeUTF8));
    label_33->setText(QApplication::translate("MainWindow", "Max Z:", 0, QApplication::UnicodeUTF8));
    tab_widget->setTabText(tab_widget->indexOf(tools_tab), QApplication::translate("MainWindow", "Tools", 0, QApplication::UnicodeUTF8));
    label_21->setText(QApplication::translate("MainWindow", "Gaussian", 0, QApplication::UnicodeUTF8));
    guassian_close_Button->setText(QApplication::translate("MainWindow", "Close", 0, QApplication::UnicodeUTF8));
    toolButton_25->setText(QApplication::translate("MainWindow", "Start", 0, QApplication::UnicodeUTF8));
    label_22->setText(QApplication::translate("MainWindow", "Variance:", 0, QApplication::UnicodeUTF8));
    label_24->setText(QApplication::translate("MainWindow", "Kernel:", 0, QApplication::UnicodeUTF8));
    label_25->setText(QApplication::translate("MainWindow", "Median", 0, QApplication::UnicodeUTF8));
    median_close_Button->setText(QApplication::translate("MainWindow", "Close", 0, QApplication::UnicodeUTF8));
    toolButton_27->setText(QApplication::translate("MainWindow", "Start", 0, QApplication::UnicodeUTF8));
    label_26->setText(QApplication::translate("MainWindow", "Radius:", 0, QApplication::UnicodeUTF8));
    label_19->setText(QApplication::translate("MainWindow", "Ignore Bins:", 0, QApplication::UnicodeUTF8));
    label_20->setText(QApplication::translate("MainWindow", "Alpha:", 0, QApplication::UnicodeUTF8));
    label_23->setText(QApplication::translate("MainWindow", "Histogram", 0, QApplication::UnicodeUTF8));
    toolButton_12->setText(QApplication::translate("MainWindow", "Start", 0, QApplication::UnicodeUTF8));
    histogram_close_Button->setText(QApplication::translate("MainWindow", "Close", 0, QApplication::UnicodeUTF8));
    tab_widget->setTabText(tab_widget->indexOf(Filter_tab), QApplication::translate("MainWindow", "Filters", 0, QApplication::UnicodeUTF8));
    groupBox->setTitle(QApplication::translate("MainWindow", "Image", 0, QApplication::UnicodeUTF8));
    pushButton_5->setText(QApplication::translate("MainWindow", "Single ", 0, QApplication::UnicodeUTF8));
    pushButton_6->setText(QApplication::translate("MainWindow", "Sequence", 0, QApplication::UnicodeUTF8));
    groupBox_2->setTitle(QApplication::translate("MainWindow", "Movie", 0, QApplication::UnicodeUTF8));
    pushButton_7->setText(QApplication::translate("MainWindow", "Start", 0, QApplication::UnicodeUTF8));
    pushButton_8->setText(QApplication::translate("MainWindow", "Stop", 0, QApplication::UnicodeUTF8));
    pushButton_9->setText(QApplication::translate("MainWindow", "Pause", 0, QApplication::UnicodeUTF8));
    pushButton_10->setText(QApplication::translate("MainWindow", "Play", 0, QApplication::UnicodeUTF8));
    label->setText(QApplication::translate("MainWindow", "Camera Path", 0, QApplication::UnicodeUTF8));
    pushButton_11->setText(QApplication::translate("MainWindow", "Add new View", 0, QApplication::UnicodeUTF8));
    pushButton_12->setText(QApplication::translate("MainWindow", "Delete Last View", 0, QApplication::UnicodeUTF8));
    pushButton_13->setText(QApplication::translate("MainWindow", "Clear All Views", 0, QApplication::UnicodeUTF8));
    tab_widget->setTabText(tab_widget->indexOf(Recorder_tab), QApplication::translate("MainWindow", "Recorder", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_IMAGEVIS3D_H
