######################################################################
# Generated by Jens Krueger
######################################################################

TEMPLATE          = app
CONFIG           += link_prl static
TARGET            = Build
DEPENDPATH       += .
INCLUDEPATH      += .
QT               += opengl
LIBS              = -L../Tuvok/Build -lTuvok

# Input
HEADERS += DebugOut/HRConsoleOut.h


SOURCES += DebugOut/HRConsoleOut.cpp \
           main.cpp
